import { Task, WorkLog, WeeklyWorkLogSubmission, TaskStatus, TaskPriority, TaskType, TaskProcessStatus } from './types';

export const MOCK_WEEKLY_SUBMISSIONS: WeeklyWorkLogSubmission[] = [
  {
    id: 'SUB-001',
    userId: 'USER-ADMIN',
    userName: '制片人-陈总',
    weekRange: '04月06日 - 04月12日',
    startDate: '2026-04-06',
    submittedAt: '2026-04-12T18:30:00Z',
    status: 'pending',
    approvalRecords: []
  },
  {
    id: 'SUB-002',
    userId: 'USER-ADMIN',
    userName: '制片人-陈总',
    weekRange: '03月30日 - 04月05日',
    startDate: '2026-03-30',
    submittedAt: '2026-04-05T19:00:00Z',
    status: 'approved',
    approvalRecords: [
      {
        id: 'REC-001',
        approverName: '财务总监',
        status: 'approved',
        comment: '工时核对无误，予以通过。',
        time: '2026-04-06T10:00:00Z'
      }
    ]
  },
  {
    id: 'SUB-003',
    userId: 'USER-ADMIN',
    userName: '制片人-陈总',
    weekRange: '03月23日 - 03月29日',
    startDate: '2026-03-23',
    submittedAt: '2026-03-29T20:15:00Z',
    status: 'rejected',
    approvalRecords: [
      {
        id: 'REC-002',
        approverName: '项目经理',
        status: 'rejected',
        comment: '3月25日工时描述过于简略，请补充细节。',
        time: '2026-03-30T09:30:00Z'
      }
    ]
  }
];

export const MOCK_TASKS: Task[] = [
  // Project: 流浪地球 3 (PROJ-001)
  {
    id: 'TASK-101',
    name: '张三角色高模制作',
    description: '根据原画设定完成主角张三的高精度模型制作，注意面部布线。',
    projectId: 'PROJ-001',
    projectName: '流浪地球 3',
    projectStatus: '进行中',
    projectDirector: '郭帆',
    projectLead: '龚格尔',
    type: TaskType.Asset,
    assetType: '角色',
    status: TaskStatus.Doing,
    processStatus: TaskProcessStatus.Processing,
    priority: TaskPriority.High,
    progress: 95,
    productionSessionIds: ['SESSION-001'],
    assetIds: ['ASSET-01', 'ASSET-02'],
    pipelineStepId: 'STEP-MODELING',
    plannedStartDate: '2026-03-10',
    plannedEndDate: '2026-03-25',
    actualStartDate: '2026-03-10',
    overdueTime: '2026-03-30',
    plannedHours: 40,
    attendanceHours: 48,
    dutyHours: 45,
    actualHours: 42,
    assigneeId: 'USER-01',
    assigneeName: '建模师-老王',
    assigneeAvatar: 'https://picsum.photos/seed/user1/40/40',
    participantNames: ['助理 A', '助理 B'],
    reviewerName: '艺术总监-老张',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-03-10T10:00:00Z',
    reviewIteration: 1,
    reviewVersion: 'v1.0.1',
    dccTools: ['Maya', 'ZBrush'],
    clockInRecords: [
      { id: 'CI-001', userId: 'USER-01', userName: '建模师-老王', startTime: '2026-03-10T09:00:00Z', endTime: '2026-03-10T18:00:00Z', duration: 8, status: 'completed' },
      { id: 'CI-002', userId: 'USER-01', userName: '建模师-老王', startTime: '2026-03-11T09:15:00Z', endTime: '2026-03-11T19:00:00Z', duration: 8.5, status: 'completed' }
    ],
    activityLogs: [
      { id: 'LOG-001', userId: 'USER-ADMIN', userName: '系统管理员', action: '创建任务', timestamp: '2026-03-10T10:00:00Z', type: 'creation' },
      { id: 'LOG-002', userId: 'USER-01', userName: '建模师-老王', action: '状态更新: 待开始 -> 制作中', timestamp: '2026-03-10T14:30:00Z', type: 'status_change', details: '正式开始执行Maya建模流程' },
      { id: 'LOG-003', userId: 'USER-01', userName: '建模师-老王', action: '修改了计划结束时间', timestamp: '2026-03-12T09:00:00Z', type: 'modification', details: '原定 3-20，调整为 3-22' },
      { id: 'LOG-004', userId: 'USER-01', userName: '建模师-老王', action: '上传了预览图', timestamp: '2026-03-15T16:00:00Z', type: 'submission', details: '初步完成身体模型' }
    ],
    versions: [
      { id: 'V-001', taskId: 'TASK-901', taskName: '角色高模制作', versionNumber: 'v001', publisherId: 'USER-01', publisherName: '建模师-老王', publishedAt: '2026-03-15T16:00:00Z', description: '初步完成身体模型', status: 'approved' },
      { id: 'V-002', taskId: 'TASK-901', taskName: '角色高模制作', versionNumber: 'v002', publisherId: 'USER-01', publisherName: '建模师-老王', publishedAt: '2026-03-17T10:00:00Z', description: '添加衣服细节', status: 'pending' }
    ],
    materials: [
      { id: 'MAT-001', name: '角色原画设计稿.jpg', type: 'image', url: 'https://picsum.photos/seed/ref1/800/600', size: '2.4MB', uploadedBy: '导演-张三', uploadedAt: '2026-03-08T10:00:00Z', category: 'reference' },
      { id: 'MAT-002', name: '角色比例参考.pdf', type: 'file', url: '#', size: '15.2MB', uploadedBy: '导演-张三', uploadedAt: '2026-03-08T10:30:00Z', category: 'reference' },
      { id: 'MAT-003', name: 'Maya身体初模_v001.mb', type: 'file', url: '#', size: '45.8MB', uploadedBy: '建模师-老王', uploadedAt: '2026-03-15T15:50:00Z', category: 'work_in_progress' },
      { id: 'MAT-004', name: '身体渲染预览_01.png', type: 'image', url: 'https://picsum.photos/seed/view1/800/600', size: '1.2MB', uploadedBy: '建模师-老王', uploadedAt: '2026-03-15T16:00:00Z', category: 'work_in_progress' }
    ],
    thumbnail: 'https://picsum.photos/seed/character/100/100',
    gifUrl: 'https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHJqZ3h5Z3h5Z3h5Z3h5Z3h5Z3h5Z3h5Z3h5Z3h5Z3h5Z3/3o7TKDkDbIDJieKbVm/giphy.gif',
    labels: ['核心资产', '高模'],
    attachmentsCount: 3,
    commentsCount: 5,
    approvalRecords: [
      {
        id: 'AR-T101-1',
        approverName: '艺术总监',
        status: 'approved',
        comment: '模型细节非常到位，符合预期。',
        time: '2026-03-20T14:00:00Z'
      }
    ]
  },
  {
    id: 'TASK-102',
    name: '场景 A 气氛图绘制',
    description: '完成场景 A 的概念气氛图，体现末世荒凉感。',
    projectId: 'PROJ-001',
    projectName: '流浪地球 3',
    projectStatus: '进行中',
    projectDirector: '郭帆',
    projectLead: '龚格尔',
    type: TaskType.Asset,
    assetType: '场景',
    status: TaskStatus.Todo,
    processStatus: TaskProcessStatus.PendingDispatch,
    priority: TaskPriority.Medium,
    progress: 0,
    assetIds: ['ASSET-SCENE-A'],
    pipelineStepId: 'STEP-CONCEPT',
    plannedStartDate: '2026-03-12',
    plannedEndDate: '2026-03-18',
    plannedHours: 16,
    attendanceHours: 0,
    dutyHours: 0,
    actualHours: 0,
    assigneeId: 'USER-02',
    assigneeName: '概念师-小李',
    assigneeAvatar: 'https://picsum.photos/seed/user2/40/40',
    participantNames: [],
    reviewerName: '艺术总监-老张',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-03-12T09:00:00Z',
    reviewIteration: 0,
    labels: ['概念图'],
    attachmentsCount: 1,
    commentsCount: 2
  },
  {
    id: 'TASK-103',
    name: '镜头 SH010 合成',
    description: '完成 SH010 镜头的背景替换与粒子特效合成。',
    projectId: 'PROJ-001',
    projectName: '流浪地球 3',
    type: TaskType.Shot,
    status: TaskStatus.Review,
    processStatus: TaskProcessStatus.Auditing,
    priority: TaskPriority.High,
    progress: 90,
    shotId: 'SHOT-010',
    pipelineStepId: 'STEP-COMPOSITING',
    plannedStartDate: '2026-03-14',
    plannedEndDate: '2026-03-17',
    actualStartDate: '2026-03-14T14:00:00Z',
    plannedHours: 24,
    attendanceHours: 38,
    dutyHours: 35,
    actualHours: 32,
    approvedHours: 28,
    submissionTime: '2026-03-17T12:00:00Z',
    assigneeId: 'USER-03',
    assigneeName: '合成师-阿强',
    assigneeAvatar: 'https://picsum.photos/seed/user3/40/40',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-03-14T14:00:00Z',
    reviewIteration: 1,
    thumbnail: 'https://picsum.photos/seed/shot/100/100',
    labels: ['特效镜头'],
    attachmentsCount: 8,
    commentsCount: 12
  },
  {
    id: 'TASK-104',
    name: '主角飞船材质贴图',
    description: '高精度飞船材质贴图，使用 Substance Painter 制作。',
    projectId: 'PROJ-001',
    projectName: '流浪地球 3',
    type: TaskType.Asset,
    status: TaskStatus.Doing,
    processStatus: TaskProcessStatus.Processing,
    priority: TaskPriority.High,
    progress: 80,
    productionSessionIds: ['SESSION-001'],
    assetIds: ['ASSET-02'],
    pipelineStepId: 'STEP-TEXTURING',
    plannedStartDate: '2026-03-15',
    plannedEndDate: '2026-03-22',
    plannedHours: 40,
    attendanceHours: 32,
    dutyHours: 30,
    actualHours: 28,
    approvedHours: 24,
    assigneeId: 'USER-01',
    assigneeName: '建模师-老王',
    assigneeAvatar: 'https://picsum.photos/seed/user1/40/40',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-03-15T09:00:00Z',
    reviewIteration: 0,
    thumbnail: 'https://picsum.photos/seed/texture/100/100',
    labels: ['核心资产', '贴图'],
    attachmentsCount: 5,
    commentsCount: 15
  },
  {
    id: 'TASK-105',
    name: '粒子系统优化',
    description: '优化烟雾粒子系统的性能，减少显存占用。',
    projectId: 'PROJ-001',
    projectName: '流浪地球 3',
    type: TaskType.Asset,
    status: TaskStatus.Doing,
    processStatus: TaskProcessStatus.Processing,
    priority: TaskPriority.Medium,
    progress: 30,
    plannedStartDate: '2026-03-12',
    plannedEndDate: '2026-03-20',
    plannedHours: 32,
    attendanceHours: 12,
    dutyHours: 12,
    actualHours: 10,
    assigneeId: 'USER-03',
    assigneeName: '合成师-阿强',
    assigneeAvatar: 'https://picsum.photos/seed/user3/40/40',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-03-12T11:00:00Z',
    reviewIteration: 0,
    labels: ['优化', '性能'],
    attachmentsCount: 0,
    commentsCount: 5
  },
  {
    id: 'TASK-108',
    name: '骨骼绑定 - 战士',
    description: '为战士角色建立完整的骨骼绑定系统。',
    projectId: 'PROJ-001',
    projectName: '流浪地球 3',
    type: TaskType.Asset,
    status: TaskStatus.Paused,
    processStatus: TaskProcessStatus.AssignRejected,
    priority: TaskPriority.High,
    progress: 45,
    plannedStartDate: '2026-03-10',
    plannedEndDate: '2026-03-20',
    plannedHours: 48,
    attendanceHours: 24,
    dutyHours: 20,
    actualHours: 22,
    assigneeId: 'USER-01',
    assigneeName: '建模师-老王',
    assigneeAvatar: 'https://picsum.photos/seed/user1/40/40',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-03-10T11:00:00Z',
    reviewIteration: 0,
    labels: ['绑定', '动画'],
    attachmentsCount: 4,
    commentsCount: 20
  },
  {
    id: 'TASK-110',
    name: '飞船引擎细节雕刻',
    description: '对飞船引擎进行超高精度细节雕刻，增加机械感。',
    projectId: 'PROJ-001',
    projectName: '流浪地球 3',
    type: TaskType.Asset,
    status: TaskStatus.Doing,
    processStatus: TaskProcessStatus.Processing,
    priority: TaskPriority.High,
    progress: 85,
    assetIds: ['ASSET-02'],
    pipelineStepId: 'STEP-MODELING',
    plannedStartDate: '2026-03-15',
    plannedEndDate: '2026-03-22',
    plannedHours: 40,
    attendanceHours: 60,
    dutyHours: 55,
    actualHours: 52,
    assigneeId: 'USER-01',
    assigneeName: '建模师-老王',
    assigneeAvatar: 'https://picsum.photos/seed/user1/40/40',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-03-15T09:00:00Z',
    reviewIteration: 0,
    thumbnail: 'https://picsum.photos/seed/spaceship/100/100',
    labels: ['核心资产', '高模'],
    attachmentsCount: 2,
    commentsCount: 8
  },
  {
    id: 'TASK-106',
    name: '李四角色表情绑定',
    projectId: 'PROJ-001',
    projectName: '流浪地球 3',
    pipelineStepId: 'Rigging',
    status: TaskStatus.Doing,
    processStatus: TaskProcessStatus.Processing,
    priority: TaskPriority.Medium,
    type: TaskType.Asset,
    plannedStartDate: '2026-03-20',
    plannedEndDate: '2026-03-30',
    plannedHours: 32,
    attendanceHours: 40,
    dutyHours: 35,
    actualHours: 12,
    assigneeId: 'USER-04',
    assigneeName: '动捕师-阿伟',
    assigneeAvatar: 'https://picsum.photos/seed/user4/40/40',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-03-20T09:00:00Z',
    reviewIteration: 0,
    thumbnail: 'https://picsum.photos/seed/face/100/100',
    assetIds: ['ASSET-002'],
    labels: ['表情', '绑定'],
    description: '李四角色表情绑定工作，包含常用口型与表情基感。',
    progress: 35,
    attachmentsCount: 1,
    commentsCount: 2
  },
  {
    id: 'TASK-107',
    name: '月球基地环境氛围图',
    projectId: 'PROJ-002',
    projectName: '三体：黑暗森林',
    pipelineStepId: 'Concept',
    status: TaskStatus.Done,
    processStatus: TaskProcessStatus.Finished,
    priority: TaskPriority.High,
    type: TaskType.Asset,
    plannedStartDate: '2026-03-01',
    plannedEndDate: '2026-03-10',
    plannedHours: 48,
    attendanceHours: 50,
    dutyHours: 48,
    actualHours: 46,
    assigneeId: 'USER-02',
    assigneeName: '概念师-小李',
    assigneeAvatar: 'https://picsum.photos/seed/user2/40/40',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-03-01T09:00:00Z',
    reviewIteration: 1,
    thumbnail: 'https://picsum.photos/seed/moon/100/100',
    assetIds: ['ASSET-003'],
    labels: ['氛围图', '月球'],
    description: '月球基地的概念设定图，需体现科幻感。',
    progress: 100,
    attachmentsCount: 3,
    commentsCount: 5
  },
  {
    id: 'TASK-112',
    name: '水滴表面材质打磨',
    projectId: 'PROJ-002',
    projectName: '三体：黑暗森林',
    pipelineStepId: 'Texture',
    status: TaskStatus.Doing,
    processStatus: TaskProcessStatus.Processing,
    priority: TaskPriority.Urgent,
    type: TaskType.Asset,
    plannedStartDate: '2026-04-15',
    plannedEndDate: '2026-04-25',
    plannedHours: 24,
    attendanceHours: 32,
    dutyHours: 28,
    actualHours: 18,
    assigneeId: 'USER-01',
    assigneeName: '建模师-老王',
    assigneeAvatar: 'https://picsum.photos/seed/user1/40/40',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-04-15T10:00:00Z',
    reviewIteration: 0,
    thumbnail: 'https://picsum.photos/seed/droplet/100/100',
    assetIds: ['ASSET-004'],
    description: '水滴表面的强相互作用材质模拟与打磨。',
    progress: 75,
    labels: ['材质', '核心'],
    attachmentsCount: 0,
    commentsCount: 1
  },
  {
    id: 'TASK-109',
    name: '直升机起飞特效',
    projectId: 'PROJ-001',
    projectName: '流浪地球 3',
    pipelineStepId: 'FX',
    status: TaskStatus.Todo,
    processStatus: TaskProcessStatus.NotStarted,
    priority: TaskPriority.Medium,
    type: TaskType.Shot,
    plannedStartDate: '2026-04-20',
    plannedEndDate: '2026-05-05',
    plannedHours: 64,
    attendanceHours: 0,
    dutyHours: 0,
    actualHours: 0,
    assigneeId: 'USER-03',
    assigneeName: '合成师-阿强',
    assigneeAvatar: 'https://picsum.photos/seed/user3/40/40',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-04-18T10:00:00Z',
    reviewIteration: 0,
    thumbnail: 'https://picsum.photos/seed/heli/100/100',
    assetIds: ['ASSET-005'],
    description: '直升机起飞时的灰尘与热量气流效果。',
    progress: 0,
    labels: ['特效'],
    attachmentsCount: 0,
    commentsCount: 0
  },
  {
    id: 'TASK-111',
    name: '巨物入侵场景合成',
    projectId: 'PROJ-001',
    projectName: '流浪地球 3',
    pipelineStepId: 'Lighting',
    status: TaskStatus.Doing,
    processStatus: TaskProcessStatus.Pause,
    priority: TaskPriority.High,
    type: TaskType.Shot,
    plannedStartDate: '2026-05-01',
    plannedEndDate: '2026-05-15',
    plannedHours: 80,
    attendanceHours: 0,
    dutyHours: 0,
    actualHours: 0,
    assigneeId: 'USER-03',
    assigneeName: '合成师-阿强',
    assigneeAvatar: 'https://picsum.photos/seed/user3/40/40',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-04-19T10:00:00Z',
    reviewIteration: 0,
    thumbnail: 'https://picsum.photos/seed/giant/100/100',
    assetIds: ['ASSET-010'],
    description: '复杂的巨物入侵场景最终灯光与合成。',
    progress: 10,
    labels: ['合成'],
    attachmentsCount: 0,
    commentsCount: 0
  },
  {
    id: 'TASK-201',
    name: '角色肌肉系统测试',
    projectId: 'PROJ-001',
    projectName: '流浪地球 3',
    pipelineStepId: 'Simulation',
    status: TaskStatus.Doing,
    processStatus: TaskProcessStatus.Processing,
    priority: TaskPriority.Medium,
    type: TaskType.Asset,
    plannedStartDate: '2026-03-10',
    plannedEndDate: '2026-03-20',
    plannedHours: 40,
    attendanceHours: 45,
    dutyHours: 42,
    actualHours: 38,
    assigneeId: 'USER-04',
    assigneeName: '动捕师-阿伟',
    assigneeAvatar: 'https://picsum.photos/seed/user4/40/40',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-03-05T09:00:00Z',
    reviewIteration: 2,
    thumbnail: 'https://picsum.photos/seed/muscle/100/100',
    assetIds: ['ASSET-002'],
    description: '使用 Ziva 或 Carbon 进行写实角色肌肉模拟测试。',
    progress: 95,
    labels: ['模拟', '核心'],
    attachmentsCount: 2,
    commentsCount: 4
  },
  {
    id: 'TASK-202',
    name: '室内灯光氛围设定',
    projectId: 'PROJ-003',
    projectName: '黑神话：悟空',
    pipelineStepId: 'Lighting',
    status: TaskStatus.Done,
    processStatus: TaskProcessStatus.Finished,
    priority: TaskPriority.High,
    type: TaskType.Shot,
    plannedStartDate: '2026-04-05',
    plannedEndDate: '2026-04-12',
    plannedHours: 32,
    attendanceHours: 40,
    dutyHours: 35,
    actualHours: 34,
    assigneeId: 'USER-01',
    assigneeName: '建模师-老王',
    assigneeAvatar: 'https://picsum.photos/seed/user1/40/40',
    creatorId: 'USER-01',
    creatorName: '建模师-老王',
    createdAt: '2026-04-05T08:00:00Z',
    reviewIteration: 1,
    thumbnail: 'https://picsum.photos/seed/light/100/100',
    description: '古代室内灯光环境氛围设定，需重点突出禅意。',
    progress: 100,
    labels: ['灯光'],
    attachmentsCount: 1,
    commentsCount: 2
  },
  {
    id: 'TASK-203',
    name: '草坪植物群落模拟',
    projectId: 'PROJ-003',
    projectName: '黑神话：悟空',
    pipelineStepId: 'Layout',
    status: TaskStatus.Doing,
    processStatus: TaskProcessStatus.Processing,
    priority: TaskPriority.Medium,
    type: TaskType.Asset,
    plannedStartDate: '2026-04-01',
    plannedEndDate: '2026-04-15',
    plannedHours: 60,
    attendanceHours: 80,
    dutyHours: 70,
    actualHours: 65,
    assigneeId: 'USER-01',
    assigneeName: '建模师-老王',
    assigneeAvatar: 'https://picsum.photos/seed/user1/40/40',
    creatorId: 'USER-01',
    creatorName: '建模师-老王',
    createdAt: '2026-04-01T10:00:00Z',
    reviewIteration: 0,
    thumbnail: 'https://picsum.photos/seed/grass/100/100',
    description: '使用 Houdini 散射技术制作写实植物群落。',
    progress: 100,
    labels: ['地貌'],
    attachmentsCount: 0,
    commentsCount: 2
  },
  {
    id: 'TASK-301',
    name: 'UI 图标重绘',
    projectId: 'PROJ-001',
    projectName: '流浪地球 3',
    pipelineStepId: 'Design',
    status: TaskStatus.Done,
    processStatus: TaskProcessStatus.Finished,
    priority: TaskPriority.Low,
    type: TaskType.Asset,
    plannedStartDate: '2026-03-25',
    plannedEndDate: '2026-03-28',
    plannedHours: 8,
    attendanceHours: 10,
    dutyHours: 9,
    actualHours: 8,
    assigneeId: 'USER-02',
    assigneeName: '概念师-小李',
    assigneeAvatar: 'https://picsum.photos/seed/user2/40/40',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-03-25T09:00:00Z',
    reviewIteration: 0,
    thumbnail: 'https://picsum.photos/seed/icons/100/100',
    description: '所有的交互 UI 图标风格统一化重绘。',
    progress: 100,
    labels: ['UI'],
    attachmentsCount: 1,
    commentsCount: 0
  },
  {
    id: 'TASK-302',
    name: '云层效果渲染测试',
    projectId: 'PROJ-001',
    projectName: '流浪地球 3',
    pipelineStepId: 'FX',
    status: TaskStatus.Doing,
    processStatus: TaskProcessStatus.Processing,
    priority: TaskPriority.Medium,
    type: TaskType.Shot,
    plannedStartDate: '2026-04-01',
    plannedEndDate: '2026-04-10',
    plannedHours: 24,
    attendanceHours: 30,
    dutyHours: 28,
    actualHours: 26,
    assigneeId: 'USER-03',
    assigneeName: '合成师-阿强',
    assigneeAvatar: 'https://picsum.photos/seed/user3/40/40',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-04-01T09:00:00Z',
    reviewIteration: 1,
    thumbnail: 'https://picsum.photos/seed/cloud/100/100',
    description: '使用 Redshift 渲染体积云的效果测试。',
    progress: 100,
    labels: ['渲染'],
    attachmentsCount: 1,
    commentsCount: 1
  },
  {
    id: 'TASK-303',
    name: '飞船引擎细节雕刻',
    projectId: 'PROJ-001',
    projectName: '流浪地球 3',
    pipelineStepId: 'Modeling',
    status: TaskStatus.Doing,
    processStatus: TaskProcessStatus.Processing,
    priority: TaskPriority.High,
    type: TaskType.Asset,
    plannedStartDate: '2026-03-05',
    plannedEndDate: '2026-03-25',
    plannedHours: 80,
    attendanceHours: 100,
    dutyHours: 90,
    actualHours: 85,
    assigneeId: 'USER-01',
    assigneeName: '建模师-老王',
    assigneeAvatar: 'https://picsum.photos/seed/user1/40/40',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-03-01T09:00:00Z',
    reviewIteration: 3,
    thumbnail: 'https://picsum.photos/seed/engine/100/100',
    description: '主力飞船引擎部分的精细化 ZBrush 雕刻。',
    progress: 100,
    labels: ['高模'],
    attachmentsCount: 1,
    commentsCount: 5
  },
  {
    id: 'TASK-304',
    name: '群落动画效果导出',
    projectId: 'PROJ-001',
    projectName: '流浪地球 3',
    pipelineStepId: 'Animation',
    status: TaskStatus.Todo,
    processStatus: TaskProcessStatus.NotStarted,
    priority: TaskPriority.Low,
    type: TaskType.Asset,
    plannedStartDate: '2026-05-10',
    plannedEndDate: '2026-05-15',
    plannedHours: 16,
    attendanceHours: 0,
    dutyHours: 0,
    actualHours: 0,
    assigneeId: 'USER-04',
    assigneeName: '动捕师-阿伟',
    assigneeAvatar: 'https://picsum.photos/seed/user4/40/40',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-05-01T10:00:00Z',
    reviewIteration: 0,
    thumbnail: 'https://picsum.photos/seed/crowd/100/100',
    description: '大量的背景群落角色动画导出为 FBX。',
    progress: 0,
    labels: ['动画'],
    attachmentsCount: 0,
    commentsCount: 0
  },
  {
    id: 'TASK-901',
    name: '2026 Q3 品牌广告提案',
    description: '制定第三季度的品牌推广方案，包含社交媒体、线下路演及电视广告组合。',
    projectId: 'PROJ-MKT',
    projectName: '市场推广部',
    projectStatus: '活动中',
    type: TaskType.Other,
    status: TaskStatus.Doing,
    processStatus: TaskProcessStatus.Processing,
    priority: TaskPriority.High,
    progress: 40,
    plannedStartDate: '2026-04-25',
    plannedEndDate: '2026-05-10',
    plannedHours: 32,
    attendanceHours: 12,
    dutyHours: 8,
    actualHours: 10,
    approvedHours: 8,
    assigneeId: 'USER-ADMIN',
    assigneeName: '制片人-陈总',
    assigneeAvatar: 'https://picsum.photos/seed/chen/40/40',
    participantNames: ['市场-小周', '视觉-老李'],
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-04-20T10:00:00Z',
    labels: ['市场', '提案', '创意设计'],
    attachmentsCount: 2,
    commentsCount: 3,
    reviewIteration: 1
  },
  {
    id: 'TASK-902',
    name: '《流浪地球3》法务合规审核',
    description: '针对项目最新的外部合作合同进行法务条款审核，确保知识产权保护到位。',
    projectId: 'PROJ-CORP',
    projectName: '集团合规部',
    projectStatus: '常态化',
    type: TaskType.Other,
    status: TaskStatus.Doing,
    processStatus: TaskProcessStatus.Processing,
    priority: TaskPriority.Urgent,
    progress: 75,
    plannedStartDate: '2026-04-28',
    plannedEndDate: '2026-04-30',
    plannedHours: 8,
    attendanceHours: 6,
    dutyHours: 0,
    actualHours: 6,
    approvedHours: 6,
    assigneeId: 'USER-LEGAL',
    assigneeName: '法务-王律师',
    assigneeAvatar: 'https://picsum.photos/seed/legal/40/40',
    creatorId: 'USER-ADMIN',
    creatorName: '制片人-陈总',
    createdAt: '2026-04-27T14:00:00Z',
    labels: ['法务', '合同', '保密'],
    attachmentsCount: 1,
    commentsCount: 1,
    reviewIteration: 2
  },
  {
    id: 'TASK-903',
    name: '季度团建方案策划',
    description: '策划夏季员工团建活动，包含选址、预算、流程安排及餐饮。',
    projectId: 'PROJ-HR',
    projectName: '人力资源部',
    projectStatus: '进行中',
    type: TaskType.Other,
    status: TaskStatus.Todo,
    processStatus: TaskProcessStatus.PendingDispatch,
    priority: TaskPriority.Low,
    progress: 0,
    plannedStartDate: '2026-05-15',
    plannedEndDate: '2026-05-20',
    plannedHours: 12,
    attendanceHours: 0,
    dutyHours: 0,
    actualHours: 0,
    approvedHours: 0,
    assigneeId: 'USER-HR',
    assigneeName: 'HR-张姐',
    assigneeAvatar: 'https://picsum.photos/seed/hr/40/40',
    creatorId: 'USER-HR',
    creatorName: 'HR-张姐',
    createdAt: '2026-04-25T11:00:00Z',
    labels: ['行政', '团建'],
    attachmentsCount: 0,
    commentsCount: 0,
    reviewIteration: 0
  }
];

export const MOCK_WORK_LOGS: WorkLog[] = [
  // User: 老王 (USER-01)
  {
    id: 'LOG-001',
    taskId: 'TASK-101',
    taskName: '张三角色高模制作',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-03-10',
    clockInHours: 8,
    actualHours: 7.5,
    approvedHours: 7.5,
    attendanceHours: 8,
    status: 'approved',
    description: '完成了头部的精细雕刻，优化了面部拓扑。'
  },
  {
    id: 'LOG-002',
    taskId: 'TASK-101',
    taskName: '张三角色高模制作',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-03-11',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '开始雕刻身体肌肉结构，完成了躯干部分。'
  },
  {
    id: 'LOG-003',
    taskId: 'TASK-101',
    taskName: '张三角色高模制作',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-03-12',
    clockInHours: 9,
    actualHours: 6.5,
    approvedHours: 4.5,
    attendanceHours: 12,
    status: 'approved',
    description: '完成了四肢的肌肉雕刻，开始进行装备基础建模。'
  },
  {
    id: 'LOG-004',
    taskId: 'TASK-108',
    taskName: '骨骼绑定 - 战士',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-03-13',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '完成了腿部骨骼的放置 and 基础权重。'
  },
  {
    id: 'LOG-005',
    taskId: 'TASK-302',
    taskName: '动捕数据清理 - 战士',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-03-14',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '清理了第 1-100 帧的抖动数据。'
  },
  {
    id: 'LOG-006',
    taskId: 'TASK-302',
    taskName: '动捕数据清理 - 战士',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-03-15',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '清理了第 101-300 帧的抖动数据。'
  },
  {
    id: 'LOG-007',
    taskId: 'TASK-101',
    taskName: '张三角色高模制作',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-03-16',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '开始细化角色的手部和足部模型，调整了指关节的比例。'
  },
  {
    id: 'LOG-008',
    taskId: 'TASK-101',
    taskName: '张三角色高模制作',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-03-17',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '完成了手部的高模细化，开始制作角色的战术背心基础网格。'
  },
  {
    id: 'LOG-009',
    taskId: 'TASK-109',
    taskName: '贴图绘制 - 战士装备',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-03-18',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '展开了战士头盔的 UV，并开始在 Substance Painter 中绘制基础材质。'
  },
  {
    id: 'LOG-010',
    taskId: 'TASK-109',
    taskName: '贴图绘制 - 战士装备',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-03-19',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '为头盔添加了金属划痕和污渍细节，调整了粗糙度贴图。'
  },
  {
    id: 'LOG-011',
    taskId: 'TASK-101',
    taskName: '张三角色高模制作',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-03-20',
    clockInHours: 4,
    actualHours: 4,
    approvedHours: 0,
    attendanceHours: 4,
    status: 'pending',
    description: '（今日）继续细化战术背心的褶皱细节，准备下午的内部评审。'
  },

  // User: 小李 (USER-02)
  {
    id: 'LOG-101',
    taskId: 'TASK-202',
    taskName: '对白翻译 - 英文版',
    userId: 'USER-02',
    userName: '概念师-小李',
    date: '2026-03-01',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '完成了前 20 页剧本的翻译。'
  },
  {
    id: 'LOG-102',
    taskId: 'TASK-202',
    taskName: '对白翻译 - 英文版',
    userId: 'USER-02',
    userName: '概念师-小李',
    date: '2026-03-02',
    clockInHours: 8,
    actualHours: 7,
    approvedHours: 7,
    attendanceHours: 8,
    status: 'approved',
    description: '完成了后 20 页剧本的翻译，并进行了初步校对。'
  },
  {
    id: 'LOG-103',
    taskId: 'TASK-203',
    taskName: '飞船内部概念图',
    userId: 'USER-02',
    userName: '概念师-小李',
    date: '2026-03-15',
    clockInHours: 8,
    actualHours: 6,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '收集了飞船内部设计的参考资料，绘制了 3 个草图。'
  },
  {
    id: 'LOG-104',
    taskId: 'TASK-203',
    taskName: '飞船内部概念图',
    userId: 'USER-02',
    userName: '概念师-小李',
    date: '2026-03-16',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '完成了驾驶舱主控制台的详细草图，确定了按钮布局。'
  },
  {
    id: 'LOG-105',
    taskId: 'TASK-203',
    taskName: '飞船内部概念图',
    userId: 'USER-02',
    userName: '概念师-小李',
    date: '2026-03-17',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '开始进行控制台的上色工作，尝试了蓝绿色的科幻色调。'
  },
  {
    id: 'LOG-106',
    taskId: 'TASK-303',
    taskName: 'UI 界面设计 - 战斗系统',
    userId: 'USER-02',
    userName: '概念师-小李',
    date: '2026-03-18',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '设计了战斗状态下的血条和能量条，采用了动态发光效果。'
  },
  {
    id: 'LOG-107',
    taskId: 'TASK-303',
    taskName: 'UI 界面设计 - 战斗系统',
    userId: 'USER-02',
    userName: '概念师-小李',
    date: '2026-03-19',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '完成了技能图标的初稿设计，共有 6 个主动技能图标。'
  },
  {
    id: 'LOG-108',
    taskId: 'TASK-303',
    taskName: 'UI 界面设计 - 战斗系统',
    userId: 'USER-02',
    userName: '概念师-小李',
    date: '2026-03-20',
    clockInHours: 4,
    actualHours: 4,
    approvedHours: 0,
    attendanceHours: 4,
    status: 'pending',
    description: '（今日）正在设计伤害数字的弹出动画效果。'
  },

  // User: 阿强 (USER-03)
  {
    id: 'LOG-201',
    taskId: 'TASK-103',
    taskName: '镜头 SH010 合成',
    userId: 'USER-03',
    userName: '合成师-阿强',
    date: '2026-03-14',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '完成了 SH010 的背景抠像与替换。'
  },
  {
    id: 'LOG-202',
    taskId: 'TASK-103',
    taskName: '镜头 SH010 合成',
    userId: 'USER-03',
    userName: '合成师-阿强',
    date: '2026-03-15',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '添加了爆炸特效的粒子层，并进行了初步调色。'
  },
  {
    id: 'LOG-203',
    taskId: 'TASK-105',
    taskName: '粒子系统优化',
    userId: 'USER-03',
    userName: '阿强',
    date: '2026-03-12',
    clockInHours: 8,
    actualHours: 6,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '分析了烟雾粒子的性能瓶颈，尝试了减少粒子数量。'
  },
  {
    id: 'LOG-204',
    taskId: 'TASK-103',
    taskName: '镜头 SH010 合成',
    userId: 'USER-03',
    userName: '合成师-阿强',
    date: '2026-03-16',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '完成了 SH010 的最终调色和光效处理，提交一审。'
  },
  {
    id: 'LOG-205',
    taskId: 'TASK-105',
    taskName: '粒子系统优化',
    userId: 'USER-03',
    userName: '合成师-阿强',
    date: '2026-03-17',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '通过 GPU 实例化优化了粒子渲染，帧率提升了 30%。'
  },
  {
    id: 'LOG-206',
    taskId: 'TASK-111',
    taskName: '灯光渲染测试 - 森林场景',
    userId: 'USER-03',
    userName: '合成师-阿强',
    date: '2026-03-18',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '设置了森林场景的基础环境光和体积光。'
  },
  {
    id: 'LOG-207',
    taskId: 'TASK-111',
    taskName: '灯光渲染测试 - 森林场景',
    userId: 'USER-03',
    userName: '合成师-阿强',
    date: '2026-03-19',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '调整了树叶的透光材质效果，优化了阴影细节。'
  },
  {
    id: 'LOG-208',
    taskId: 'TASK-111',
    taskName: '灯光渲染测试 - 森林场景',
    userId: 'USER-03',
    userName: '合成师-阿强',
    date: '2026-03-20',
    clockInHours: 4,
    actualHours: 4,
    approvedHours: 0,
    attendanceHours: 4,
    status: 'pending',
    description: '（今日）正在进行森林场景的 4K 样帧渲染。'
  },

  // User: 阿伟 (USER-04)
  {
    id: 'LOG-301',
    taskId: 'TASK-301',
    taskName: '主角色动作捕捉',
    userId: 'USER-04',
    userName: '动捕师-阿伟',
    date: '2026-03-05',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 8,
    attendanceHours: 8,
    status: 'approved',
    description: '完成了行走和奔跑动作的采集。'
  },
  {
    id: 'LOG-302',
    taskId: 'TASK-301',
    taskName: '主角色动作捕捉',
    userId: 'USER-04',
    userName: '动捕师-阿伟',
    date: '2026-03-06',
    clockInHours: 8,
    actualHours: 9,
    approvedHours: 8,
    attendanceHours: 10,
    status: 'approved',
    description: '完成了跳跃和攀爬动作的采集。'
  },
  {
    id: 'LOG-303',
    taskId: 'TASK-304',
    taskName: '音效录制 - 武器打击',
    userId: 'USER-04',
    userName: '动捕师-阿伟',
    date: '2026-03-15',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '录制了金属碰撞和木材碎裂的音效。'
  },
  // Additional Logs for the current week (Mar 30 - Apr 3, 2026)
  {
    id: 'LOG-401',
    taskId: 'TASK-101',
    taskName: '张三角色高模制作',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-03-30',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '细化了角色的皮肤纹理和毛孔细节。'
  },
  {
    id: 'LOG-402',
    taskId: 'TASK-101',
    taskName: '张三角色高模制作',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-03-31',
    clockInHours: 8,
    actualHours: 9,
    approvedHours: 0,
    attendanceHours: 9,
    status: 'pending',
    description: '完成了眼球和牙齿的精细建模。'
  },
  {
    id: 'LOG-403',
    taskId: 'TASK-102',
    taskName: '场景 A 气氛图绘制',
    userId: 'USER-02',
    userName: '概念师-小李',
    date: '2026-03-30',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '绘制了场景 A 的第一版构图草稿。'
  },
  {
    id: 'LOG-404',
    taskId: 'TASK-102',
    taskName: '场景 A 气氛图绘制',
    userId: 'USER-02',
    userName: '概念师-小李',
    date: '2026-03-31',
    clockInHours: 8,
    actualHours: 10,
    approvedHours: 0,
    attendanceHours: 10,
    status: 'pending',
    description: '调整了光影布局，增加了废墟的细节。'
  },
  {
    id: 'LOG-405',
    taskId: 'TASK-102',
    taskName: '场景 A 气氛图绘制',
    userId: 'USER-02',
    userName: '概念师-小李',
    date: '2026-04-01',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '开始进行色彩铺设，确定了冷色调基调。'
  },
  {
    id: 'LOG-406',
    taskId: 'TASK-103',
    taskName: '镜头 SH010 合成',
    userId: 'USER-03',
    userName: '合成师-阿强',
    date: '2026-03-30',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '处理了 SH010 镜头中的动态模糊效果。'
  },
  {
    id: 'LOG-407',
    taskId: 'TASK-103',
    taskName: '镜头 SH010 合成',
    userId: 'USER-03',
    userName: '合成师-阿强',
    date: '2026-03-31',
    clockInHours: 8,
    actualHours: 7,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '修复了边缘锯齿问题，优化了合成质量。'
  },
  {
    id: 'LOG-408',
    taskId: 'TASK-105',
    taskName: '粒子系统优化',
    userId: 'USER-03',
    userName: '合成师-阿强',
    date: '2026-04-01',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '对烟雾粒子的生命周期进行了重新配置。'
  },
  // Historical logs for Asset Progress demonstration
  {
    id: 'LOG-HIST-001',
    taskId: 'TASK-101',
    taskName: '张三角色高模制作',
    userId: 'USER-02',
    userName: '概念师-小李',
    date: '2026-03-15',
    clockInHours: 4,
    actualHours: 4,
    approvedHours: 4,
    attendanceHours: 4,
    status: 'approved',
    description: '协助老王进行面部细节的初步调整。'
  },
  {
    id: 'LOG-HIST-002',
    taskId: 'TASK-103',
    taskName: '镜头 SH010 合成',
    userId: 'USER-04',
    userName: '动捕师-阿伟',
    date: '2026-03-16',
    clockInHours: 2,
    actualHours: 2,
    approvedHours: 2,
    attendanceHours: 2,
    status: 'approved',
    description: '提供了动捕参考帧用于合成对位。'
  },
  // --- Recent Logs for April 2026 (Current Week Simulation) ---
  {
    id: 'LOG-APR-001',
    taskId: 'TASK-101',
    taskName: '张三角色高模制作',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-04-06',
    clockInHours: 8,
    actualHours: 8.5,
    approvedHours: 0,
    attendanceHours: 9,
    status: 'pending',
    description: '完成了张三角色的面部表情基准模型（Blendshapes）制作。'
  },
  {
    id: 'LOG-APR-002',
    taskId: 'TASK-110',
    taskName: '飞船引擎细节雕刻',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-04-07',
    clockInHours: 4,
    actualHours: 4,
    approvedHours: 0,
    attendanceHours: 4,
    status: 'pending',
    description: '开始雕刻引擎内部的管线细节，增加机械复杂感。'
  },
  {
    id: 'LOG-APR-101',
    taskId: 'TASK-203',
    taskName: '飞船内部概念图',
    userId: 'USER-02',
    userName: '概念师-小李',
    date: '2026-04-06',
    clockInHours: 8,
    actualHours: 7.5,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '细化了驾驶舱的照明方案，增加了紧急状态下的红色警报灯光效果。'
  },
  {
    id: 'LOG-APR-102',
    taskId: 'TASK-303',
    taskName: 'UI 界面设计 - 战斗系统',
    userId: 'USER-02',
    userName: '概念师-小李',
    date: '2026-04-07',
    clockInHours: 4,
    actualHours: 4,
    approvedHours: 0,
    attendanceHours: 4,
    status: 'pending',
    description: '设计了战斗结算界面的布局草图，包括评分等级和奖励展示。'
  },
  {
    id: 'LOG-APR-201',
    taskId: 'TASK-103',
    taskName: '镜头 SH010 合成',
    userId: 'USER-03',
    userName: '合成师-阿强',
    date: '2026-04-06',
    clockInHours: 8,
    actualHours: 9,
    approvedHours: 0,
    attendanceHours: 10,
    status: 'pending',
    description: '根据导演反馈，调整了 SH010 镜头的爆炸火花亮度，并增加了镜头抖动。'
  },
  {
    id: 'LOG-APR-202',
    taskId: 'TASK-105',
    taskName: '粒子系统优化',
    userId: 'USER-03',
    userName: '合成师-阿强',
    date: '2026-04-07',
    clockInHours: 4,
    actualHours: 4,
    approvedHours: 0,
    attendanceHours: 4,
    status: 'pending',
    description: '测试了新的 GPU 粒子缓存方案，初步结果显示加载速度提升了 30%。'
  },
  {
    id: 'LOG-APR-301',
    taskId: 'TASK-304',
    taskName: '音效录制 - 武器打击',
    userId: 'USER-04',
    userName: '动捕师-阿伟',
    date: '2026-04-06',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '在录音棚完成了重型战斧打击石块和木板的音效采集。'
  },
  {
    id: 'LOG-APR-302',
    taskId: 'TASK-304',
    taskName: '音效录制 - 武器打击',
    userId: 'USER-04',
    userName: '动捕师-阿伟',
    date: '2026-04-07',
    clockInHours: 4,
    actualHours: 4,
    approvedHours: 0,
    attendanceHours: 4,
    status: 'pending',
    description: '整理昨日录制的音频文件，进行初步的降噪和剪辑处理。'
  },
  {
    id: 'LOG-APR-101',
    taskId: 'TASK-101',
    taskName: '张三角色高模制作',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-04-06',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '继续细化角色的盔甲纹理，增加了金属磨损效果。'
  },
  {
    id: 'LOG-APR-102',
    taskId: 'TASK-101',
    taskName: '张三角色高模制作',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-04-07',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '完成了盔甲的最终雕刻，开始准备拓扑低模。'
  },
  {
    id: 'LOG-APR-201',
    taskId: 'TASK-201',
    taskName: '场景原画 - 遗迹内部',
    userId: 'USER-02',
    userName: '原画师-小李',
    date: '2026-04-06',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '绘制了遗迹内部的光影氛围图，确定了主色调。'
  },
  {
    id: 'LOG-APR-202',
    taskId: 'TASK-201',
    taskName: '场景原画 - 遗迹内部',
    userId: 'USER-02',
    userName: '原画师-小李',
    date: '2026-04-07',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'pending',
    description: '细化了遗迹中的石柱和祭坛细节。'
  },
  {
    id: 'LOG-REJ-001',
    taskId: 'TASK-101',
    taskName: '张三角色高模制作',
    userId: 'USER-01',
    userName: '建模师-老王',
    date: '2026-04-03',
    clockInHours: 8,
    actualHours: 8,
    approvedHours: 0,
    attendanceHours: 8,
    status: 'rejected',
    description: '尝试制作了角色的发型，但效果不符合原画设定，需要重做。'
  }
];

export const MOCK_VERSIONS: any[] = [
  {
    id: 'VER-001',
    taskId: 'TASK-101',
    taskName: '张三角色高模制作',
    versionNumber: 'v001',
    publisherId: 'USER-ADMIN',
    publisherName: '制片人-陈总',
    publishedAt: '2026-03-15T10:00:00Z',
    description: '初步完成面部细节雕刻',
    thumbnail: 'https://picsum.photos/seed/ver1/100/100',
    status: 'approved',
    assetName: '主角-张三',
    assetType: 'Character',
    dependencies: [
      { id: 'ASSET-05', name: '张三概念图', type: 'Concept' },
      { id: 'ASSET-06', name: '基础人体模型', type: 'BaseMesh' }
    ],
    approvalRecords: [
      {
        id: 'AR-V1-1',
        approverName: '技术总监',
        status: 'approved',
        comment: '渲染质量很高，通过。',
        time: '2026-03-16T10:00:00Z'
      }
    ]
  },
  {
    id: 'VER-002',
    taskId: 'TASK-101',
    taskName: '张三角色高模制作',
    versionNumber: 'v002',
    publisherId: 'USER-ADMIN',
    publisherName: '制片人-陈总',
    publishedAt: '2026-03-20T14:00:00Z',
    description: '装备细节优化',
    thumbnail: 'https://picsum.photos/seed/ver2/100/100',
    status: 'pending',
    assetName: '主角-张三',
    assetType: 'Character',
    dependencies: [
      { id: 'ASSET-05', name: '张三概念图', type: 'Concept' }
    ],
    approvalRecords: []
  },
  {
    id: 'VER-003',
    taskId: 'TASK-103',
    taskName: '镜头 SH010 合成',
    versionNumber: 'v001',
    publisherId: 'USER-03',
    publisherName: '合成师-阿强',
    publishedAt: '2026-03-16T11:00:00Z',
    description: '背景抠像完成',
    thumbnail: 'https://picsum.photos/seed/ver3/100/100',
    status: 'approved'
  }
];
